@startuml P2P-matching db

entity User {
  int id
  varchar name
  int matchingPoint
  varchar githubId
  text bio
}

entity Message {
  int id
  int postId <<FK>>
  int authorId
  text content
  datetime createdAt
}

entity Post {
  int id
  varchar title
  varchar description
  int driverId <<FK>>
  int navigatorId <<FK>>
  datetime completedAt
  varchar meetingUrl
}

entity Skill { 
  int id
  varchar name
}

User ||..|{ Post
Post }|..|{ Skill
Post ||..|{ Message

@enduml
